# Change these first
owner: upptime # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Ryan Yao Design
    url: https://ryanyao.design
  - name: Ryan Yao Photos
    url: https://ryanyao.photos
  - name: Designer Slack Communnities
    url: https://www.designerslack.community
  - name: RSSHub
    url: https://rsshub.ryanyao.xyz
  - name: gram
    url: https://gram.ryanyao.xyz
  - name: Search
    url: https://search.ryanyao.xyz
  - name: tube
    url: https://tube.ryanyao.xyz
  - name: Kingge
    url: https://www.kingge.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  baseUrl: /uptime # where "repo" is your repository name
  name: Uptime Site
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

  steps:
    -name: Notifications
      env: 
        SUPER_SECRET: ${{ secrets.GH_PAT}}
        NOTIFICATION_TELEGRAM: true
        NOTIFICATION_TELEGRAM_BOT_KEY: ${{ secrets.TG_BOT}}
        NOTIFICATION_TELEGRAM_CHAT_ID: @ryandesign


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
